// <auto-generated />
using FinalProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("FinalProject.Models.Driver", b =>
                {
                    b.Property<int>("DriverID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReeferID")
                        .HasColumnType("INTEGER");

                    b.HasKey("DriverID");

                    b.HasIndex("ReeferID")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("FinalProject.Models.Reefer", b =>
                {
                    b.Property<int>("ReeferID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ReeferID");

                    b.ToTable("Reefers");
                });

            modelBuilder.Entity("FinalProject.Models.Truck", b =>
                {
                    b.Property<int>("TruckID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TruckID");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("FinalProject.Models.TruckDriver", b =>
                {
                    b.Property<int>("TruckID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DriverID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TruckID", "DriverID");

                    b.HasIndex("DriverID");

                    b.ToTable("TruckDrivers");
                });

            modelBuilder.Entity("FinalProject.Models.Driver", b =>
                {
                    b.HasOne("FinalProject.Models.Reefer", "Reefer")
                        .WithOne("Driver")
                        .HasForeignKey("FinalProject.Models.Driver", "ReeferID");

                    b.Navigation("Reefer");
                });

            modelBuilder.Entity("FinalProject.Models.TruckDriver", b =>
                {
                    b.HasOne("FinalProject.Models.Driver", "Driver")
                        .WithMany("TruckDrivers")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject.Models.Truck", "Truck")
                        .WithMany("TruckDrivers")
                        .HasForeignKey("TruckID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("FinalProject.Models.Driver", b =>
                {
                    b.Navigation("TruckDrivers");
                });

            modelBuilder.Entity("FinalProject.Models.Reefer", b =>
                {
                    b.Navigation("Driver")
                        .IsRequired();
                });

            modelBuilder.Entity("FinalProject.Models.Truck", b =>
                {
                    b.Navigation("TruckDrivers");
                });
#pragma warning restore 612, 618
        }
    }
}
